application: tryappbhargav
version: 1
runtime: php
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
  
- url: /pages
  static_dir: pages

- url: /.*
  script: startpage.php
  
- url: /.php
  script: signin.php
  
- url: /php
  script: php